In [14]:
import mysql.connector
import pandas as pd

In [15]:
cnx = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Lawrence12",
    database="sakila"
)

In [16]:
cursor = cnx.cursor()

In [26]:
query1 = """
SELECT 
    c.first_name, 
    c.last_name, 
    c.email, 
    a.address, 
    ci.city
FROM 
    customer c
JOIN 
    address a ON c.address_id = a.address_id
JOIN 
    city ci ON a.city_id = ci.city_id
WHERE 
    ci.city_id = 312;
"""
cursor.execute(query1)
result1 = cursor.fetchall()
print("Query 1 Result:")
for row in result1:
    print(row)

Query 1 Result:
('MATTIE', 'HOFFMAN', 'MATTIE.HOFFMAN@sakilacustomer.org', '1497 Yuzhou Drive', 'London')
('CECIL', 'VINES', 'CECIL.VINES@sakilacustomer.org', '548 Uruapan Street', 'London')

In [27]:
query2 = """
SELECT 
    f.title, 
    f.description, 
    f.release_year, 
    f.rating, 
    f.special_features
FROM 
    film f
JOIN 
    film_category fc ON f.film_id = fc.film_id
JOIN 
    category c ON fc.category_id = c.category_id
WHERE 
    c.name = 'Comedy';
"""
cursor.execute(query2)
result2 = cursor.fetchall()
print("\nQuery 2 Result:")
for row in result2:
    print(row)

Query 2 Result:
('AIRPLANE SIERRA', 'A Touching Saga of a Hunter And a Butler who must Discover a Butler in A Jet Boat', 2006, 'PG-13', {'Deleted Scenes', 'Trailers'})
('ANTHEM LUKE', 'A Touching Panorama of a Waitress And a Woman who must Outrace a Dog in An Abandoned Amusement Park', 2006, 'PG-13', {'Deleted Scenes', 'Behind the Scenes'})
('BRINGING HYSTERICAL', 'A Fateful Saga of a A Shark And a Technical Writer who must Find a Woman in A Jet Boat', 2006, 'PG', {'Trailers'})
('CAPER MOTIONS', 'A Fateful Saga of a Moose And a Car who must Pursue a Woman in A MySQL Convention', 2006, 'G', {'Deleted Scenes', 'Commentaries', 'Trailers'})
('CAT CONEHEADS', 'A Fast-Paced Panorama of a Girl And a A Shark who must Confront a Boy in Ancient India', 2006, 'G', {'Deleted Scenes', 'Commentaries'})
('CLOSER BANG', 'A Unbelieveable Panorama of a Frisbee And a Hunter who must Vanquish a Monkey in Ancient India', 2006, 'R', {'Trailers', 'Behind the Scenes'})
('CONNECTION MICROCOSMOS', 'A Fateful Documentary of a Crocodile And a Husband who must Face a Husband in The First Manned Space Station', 2006, 'G', {'Deleted Scenes', 'Behind the Scenes'})
('CONTROL ANTHEM', 'A Fateful Documentary of a Robot And a Student who must Battle a Cat in A Monastery', 2006, 'G', {'Commentaries'})
('CRAZY HOME', 'A Fanciful Panorama of a Boy And a Woman who must Vanquish a Database Administrator in The Outback', 2006, 'PG', {'Deleted Scenes', 'Commentaries'})
('DADDY PITTSBURGH', 'A Epic Story of a A Shark And a Student who must Confront a Explorer in The Gulf of Mexico', 2006, 'G', {'Deleted Scenes', 'Behind the Scenes'})
('DOOM DANCING', 'A Astounding Panorama of a Car And a Mad Scientist who must Battle a Lumberjack in A MySQL Convention', 2006, 'R', {'Commentaries', 'Trailers'})
('DOWNHILL ENOUGH', 'A Emotional Tale of a Pastry Chef And a Forensic Psychologist who must Succumb a Monkey in The Sahara Desert', 2006, 'G', {'Deleted Scenes', 'Commentaries', 'Trailers'})
('DYING MAKER', 'A Intrepid Tale of a Boat And a Monkey who must Kill a Cat in California', 2006, 'PG', {'Behind the Scenes'})
('ELEMENT FREDDY', 'A Awe-Inspiring Reflection of a Waitress And a Squirrel who must Kill a Mad Cow in A Jet Boat', 2006, 'NC-17', {'Commentaries', 'Behind the Scenes'})
('FERRIS MOTHER', 'A Touching Display of a Frisbee And a Frisbee who must Kill a Girl in The Gulf of Mexico', 2006, 'PG', {'Deleted Scenes', 'Trailers', 'Behind the Scenes'})
('FIREBALL PHILADELPHIA', 'A Amazing Yarn of a Dentist And a A Shark who must Vanquish a Madman in An Abandoned Mine Shaft', 2006, 'PG', {'Commentaries', 'Trailers', 'Behind the Scenes'})
('FLINTSTONES HAPPINESS', 'A Fateful Story of a Husband And a Moose who must Vanquish a Boy in California', 2006, 'PG-13', {'Deleted Scenes', 'Commentaries', 'Trailers', 'Behind the Scenes'})
('FRANKENSTEIN STRANGER', 'A Insightful Character Study of a Feminist And a Pioneer who must Pursue a Pastry Chef in Nigeria', 2006, 'NC-17', {'Deleted Scenes', 'Behind the Scenes'})
('FREEDOM CLEOPATRA', 'A Emotional Reflection of a Dentist And a Mad Cow who must Face a Squirrel in A Baloon', 2006, 'PG-13', {'Commentaries', 'Trailers', 'Behind the Scenes'})
('GOLD RIVER', 'A Taut Documentary of a Database Administrator And a Waitress who must Reach a Mad Scientist in A Baloon Factory', 2006, 'R', {'Deleted Scenes', 'Commentaries', 'Trailers', 'Behind the Scenes'})
('GROUNDHOG UNCUT', 'A Brilliant Panorama of a Astronaut And a Technical Writer who must Discover a Butler in A Manhattan Penthouse', 2006, 'PG-13', {'Deleted Scenes', 'Commentaries', 'Trailers', 'Behind the Scenes'})
('GUNFIGHT MOON', 'A Epic Reflection of a Pastry Chef And a Explorer who must Reach a Dentist in The Sahara Desert', 2006, 'NC-17', {'Deleted Scenes', 'Behind the Scenes'})
('HATE HANDICAP', 'A Intrepid Reflection of a Mad Scientist And a Pioneer who must Overcome a Hunter in The First Manned Space Station', 2006, 'PG', {'Commentaries', 'Trailers', 'Behind the Scenes'})
('HEAVEN FREEDOM', 'A Intrepid Story of a Butler And a Car who must Vanquish a Man in New Orleans', 2006, 'PG', {'Commentaries'})
('HEDWIG ALTER', 'A Action-Packed Yarn of a Womanizer And a Lumberjack who must Chase a Sumo Wrestler in A Monastery', 2006, 'NC-17', {'Commentaries', 'Trailers', 'Behind the Scenes'})
('HURRICANE AFFAIR', 'A Lacklusture Epistle of a Database Administrator And a Woman who must Meet a Hunter in An Abandoned Mine Shaft', 2006, 'PG', {'Commentaries', 'Trailers', 'Behind the Scenes'})
('HUSTLER PARTY', 'A Emotional Reflection of a Sumo Wrestler And a Monkey who must Conquer a Robot in The Sahara Desert', 2006, 'NC-17', {'Commentaries', 'Trailers', 'Behind the Scenes'})
('JAWS HARRY', 'A Thrilling Display of a Database Administrator And a Monkey who must Overcome a Dog in An Abandoned Fun House', 2006, 'G', {'Deleted Scenes'})
('KNOCK WARLOCK', 'A Unbelieveable Story of a Teacher And a Boat who must Confront a Moose in A Baloon', 2006, 'PG-13', {'Trailers'})
('LIFE TWISTED', 'A Thrilling Reflection of a Teacher And a Composer who must Find a Man in The First Manned Space Station', 2006, 'NC-17', {'Deleted Scenes', 'Commentaries'})
('LION UNCUT', 'A Intrepid Display of a Pastry Chef And a Cat who must Kill a A Shark in Ancient China', 2006, 'PG', {'Deleted Scenes', 'Trailers'})
('LONELY ELEPHANT', 'A Intrepid Story of a Student And a Dog who must Challenge a Explorer in Soviet Georgia', 2006, 'G', {'Deleted Scenes', 'Commentaries', 'Trailers', 'Behind the Scenes'})
('MALLRATS UNITED', 'A Thrilling Yarn of a Waitress And a Dentist who must Find a Hunter in A Monastery', 2006, 'PG', {'Deleted Scenes', 'Commentaries', 'Trailers'})
('MEMENTO ZOOLANDER', 'A Touching Epistle of a Squirrel And a Explorer who must Redeem a Pastry Chef in The Sahara Desert', 2006, 'NC-17', {'Behind the Scenes'})
('MULAN MOON', 'A Emotional Saga of a Womanizer And a Pioneer who must Overcome a Dentist in A Baloon', 2006, 'G', {'Behind the Scenes'})
('MYSTIC TRUMAN', 'A Epic Yarn of a Teacher And a Hunter who must Outgun a Explorer in Soviet Georgia', 2006, 'NC-17', {'Commentaries', 'Behind the Scenes'})
('OPERATION OPERATION', 'A Intrepid Character Study of a Man And a Frisbee who must Overcome a Madman in Ancient China', 2006, 'G', {'Deleted Scenes', 'Commentaries', 'Trailers', 'Behind the Scenes'})
('PARADISE SABRINA', 'A Intrepid Yarn of a Car And a Moose who must Outrace a Crocodile in A Manhattan Penthouse', 2006, 'PG-13', {'Deleted Scenes', 'Commentaries', 'Behind the Scenes'})
('PARTY KNOCK', 'A Fateful Display of a Technical Writer And a Butler who must Battle a Sumo Wrestler in An Abandoned Mine Shaft', 2006, 'PG', {'Trailers', 'Behind the Scenes'})
('PERFECT GROOVE', 'A Thrilling Yarn of a Dog And a Dog who must Build a Husband in A Baloon', 2006, 'PG-13', {'Deleted Scenes', 'Commentaries', 'Behind the Scenes'})
('PINOCCHIO SIMON', 'A Action-Packed Reflection of a Mad Scientist And a A Shark who must Find a Feminist in California', 2006, 'PG', {'Commentaries', 'Behind the Scenes'})
('PURE RUNNER', 'A Thoughtful Documentary of a Student And a Madman who must Challenge a Squirrel in A Manhattan Penthouse', 2006, 'NC-17', {'Deleted Scenes', 'Trailers'})
('RUSHMORE MERMAID', 'A Boring Story of a Woman And a Moose who must Reach a Husband in A Shark Tank', 2006, 'PG-13', {'Deleted Scenes', 'Commentaries', 'Trailers'})
('SADDLE ANTITRUST', 'A Stunning Epistle of a Feminist And a A Shark who must Battle a Woman in An Abandoned Fun House', 2006, 'PG-13', {'Deleted Scenes', 'Trailers'})
('SATURN NAME', 'A Fateful Epistle of a Butler And a Boy who must Redeem a Teacher in Berlin', 2006, 'R', {'Deleted Scenes', 'Commentaries', 'Trailers', 'Behind the Scenes'})
('SEARCHERS WAIT', 'A Fast-Paced Tale of a Car And a Mad Scientist who must Kill a Womanizer in Ancient Japan', 2006, 'NC-17', {'Deleted Scenes', 'Commentaries', 'Trailers', 'Behind the Scenes'})
('SNATCH SLIPPER', 'A Insightful Panorama of a Woman And a Feminist who must Defeat a Forensic Psychologist in Berlin', 2006, 'PG', {'Commentaries'})
('STAGE WORLD', 'A Lacklusture Panorama of a Woman And a Frisbee who must Chase a Crocodile in A Jet Boat', 2006, 'PG', {'Commentaries', 'Behind the Scenes'})
('STRICTLY SCARFACE', 'A Touching Reflection of a Crocodile And a Dog who must Chase a Hunter in An Abandoned Fun House', 2006, 'PG-13', {'Deleted Scenes', 'Commentaries', 'Behind the Scenes'})
('SUBMARINE BED', 'A Amazing Display of a Car And a Monkey who must Fight a Teacher in Soviet Georgia', 2006, 'R', {'Trailers'})
('SWEDEN SHINING', 'A Taut Documentary of a Car And a Robot who must Conquer a Boy in The Canadian Rockies', 2006, 'PG', {'Deleted Scenes', 'Behind the Scenes'})
('TRAINSPOTTING STRANGERS', 'A Fast-Paced Drama of a Pioneer And a Mad Cow who must Challenge a Madman in Ancient Japan', 2006, 'PG-13', {'Trailers'})
('TRAMP OTHERS', 'A Brilliant Display of a Composer And a Cat who must Succumb a A Shark in Ancient India', 2006, 'PG', {'Deleted Scenes'})
('VALLEY PACKER', 'A Astounding Documentary of a Astronaut And a Boy who must Outrace a Sumo Wrestler in Berlin', 2006, 'G', {'Deleted Scenes', 'Commentaries'})
('VELVET TERMINATOR', 'A Lacklusture Tale of a Pastry Chef And a Technical Writer who must Confront a Crocodile in An Abandoned Amusement Park', 2006, 'R', {'Behind the Scenes'})
('VERTIGO NORTHWEST', 'A Unbelieveable Display of a Mad Scientist And a Mad Scientist who must Outgun a Mad Cow in Ancient Japan', 2006, 'R', {'Commentaries', 'Behind the Scenes'})
('WISDOM WORKER', 'A Unbelieveable Saga of a Forensic Psychologist And a Student who must Face a Squirrel in The First Manned Space Station', 2006, 'R', {'Deleted Scenes', 'Behind the Scenes'})
('ZORRO ARK', 'A Intrepid Panorama of a Mad Scientist And a Boy who must Redeem a Boy in A Monastery', 2006, 'NC-17', {'Commentaries', 'Trailers', 'Behind the Scenes'})

In [28]:
query3 = """
SELECT 
    a.last_name, 
    f.title, 
    f.release_year
FROM 
    actor a
JOIN 
    film_actor fa ON a.actor_id = fa.actor_id
JOIN 
    film f ON fa.film_id = f.film_id
WHERE 
    a.first_name = 'Johnny' 
    AND a.last_name = 'Lollobrigida';
"""
cursor.execute(query3)
result3 = cursor.fetchall()
print("\nQuery 3 Result:")
for row in result3:
    print(row)

Query 3 Result:
('LOLLOBRIGIDA', 'AMADEUS HOLY', 2006)
('LOLLOBRIGIDA', 'BANGER PINOCCHIO', 2006)
('LOLLOBRIGIDA', 'BONNIE HOLOCAUST', 2006)
('LOLLOBRIGIDA', 'CHITTY LOCK', 2006)
('LOLLOBRIGIDA', 'COMMANDMENTS EXPRESS', 2006)
('LOLLOBRIGIDA', 'CONEHEADS SMOOCHY', 2006)
('LOLLOBRIGIDA', 'DADDY PITTSBURGH', 2006)
('LOLLOBRIGIDA', 'DAISY MENAGERIE', 2006)
('LOLLOBRIGIDA', 'ENOUGH RAGING', 2006)
('LOLLOBRIGIDA', 'ESCAPE METROPOLIS', 2006)
('LOLLOBRIGIDA', 'FIRE WOLVES', 2006)
('LOLLOBRIGIDA', 'FRONTIER CABIN', 2006)
('LOLLOBRIGIDA', 'GOODFELLAS SALUTE', 2006)
('LOLLOBRIGIDA', 'GRAIL FRANKENSTEIN', 2006)
('LOLLOBRIGIDA', 'GROOVE FICTION', 2006)
('LOLLOBRIGIDA', 'HALL CASSIDY', 2006)
('LOLLOBRIGIDA', 'HEAVENLY GUN', 2006)
('LOLLOBRIGIDA', 'KRAMER CHOCOLATE', 2006)
('LOLLOBRIGIDA', 'LOVE SUICIDES', 2006)
('LOLLOBRIGIDA', 'METAL ARMAGEDDON', 2006)
('LOLLOBRIGIDA', 'PACIFIC AMISTAD', 2006)
('LOLLOBRIGIDA', 'PATTON INTERVIEW', 2006)
('LOLLOBRIGIDA', 'POCUS PULP', 2006)
('LOLLOBRIGIDA', 'RIDGEMONT SUBMARINE', 2006)
('LOLLOBRIGIDA', 'RINGS HEARTBREAKERS', 2006)
('LOLLOBRIGIDA', 'SMILE EARRING', 2006)
('LOLLOBRIGIDA', 'SOLDIERS EVOLUTION', 2006)
('LOLLOBRIGIDA', 'STAR OPERATION', 2006)
('LOLLOBRIGIDA', 'SUNRISE LEAGUE', 2006)

In [29]:
query4 = """
SELECT 
    a.first_name, 
    a.last_name
FROM 
    actor a
JOIN 
    film_actor fa ON a.actor_id = fa.actor_id
JOIN 
    film f ON fa.film_id = f.film_id
WHERE 
    f.title = 'Bingo Talented';
"""
cursor.execute(query4)
result4 = cursor.fetchall()
print("\nQuery 4 Result:")
for row in result4:
    print(row)

Query 4 Result:
('GOLDIE', 'BRODY')
('CAMERON', 'WRAY')
('CARY', 'MCCONAUGHEY')
('JON', 'CHASE')
('RENEE', 'BALL')

In [30]:
query5 = """
SELECT 
    p.customer_id, 
    p.amount
FROM 
    payment p
WHERE 
    p.amount > (SELECT 2 * AVG(amount) FROM payment);
"""
cursor.execute(query5)
result5 = cursor.fetchall()
print("\nQuery 5 Result:")
for row in result5:
    print(row)

Query 5 Result:
(1, Decimal('9.99'))
(2, Decimal('10.99'))
(3, Decimal('8.99'))
(3, Decimal('10.99'))
(3, Decimal('8.99'))
(3, Decimal('8.99'))
(4, Decimal('8.99'))
(5, Decimal('8.99'))
(5, Decimal('9.99'))
(7, Decimal('8.99'))
(7, Decimal('8.99'))
(8, Decimal('9.99'))
(10, Decimal('8.99'))
(11, Decimal('9.99'))
(12, Decimal('10.99'))
(13, Decimal('8.99'))
(13, Decimal('8.99'))
(13, Decimal('11.99'))
(13, Decimal('9.99'))
(13, Decimal('9.99'))
(14, Decimal('9.99'))
(15, Decimal('8.99'))
(15, Decimal('8.99'))
(16, Decimal('8.99'))
(17, Decimal('8.99'))
(17, Decimal('8.99'))
(17, Decimal('8.99'))
(17, Decimal('8.99'))
(18, Decimal('8.99'))
(19, Decimal('9.99'))
(19, Decimal('9.99'))
(19, Decimal('8.99'))
(19, Decimal('9.99'))
(19, Decimal('8.99'))
(19, Decimal('8.99'))
(21, Decimal('10.99'))
(21, Decimal('8.99'))
(21, Decimal('9.99'))
(21, Decimal('8.99'))
(22, Decimal('8.99'))
(22, Decimal('9.99'))
(23, Decimal('8.99'))
(23, Decimal('9.99'))
(24, Decimal('8.99'))
(25, Decimal('8.99'))
(25, Decimal('8.99'))
(26, Decimal('9.99'))
(26, Decimal('8.99'))
(27, Decimal('8.99'))
(28, Decimal('9.99'))
(29, Decimal('10.99'))
(30, Decimal('9.99'))
(31, Decimal('9.99'))
(32, Decimal('9.99'))
(32, Decimal('9.99'))
(32, Decimal('8.99'))
(33, Decimal('10.99'))
(33, Decimal('8.99'))
(36, Decimal('9.99'))
(37, Decimal('9.99'))
(37, Decimal('8.99'))
(39, Decimal('8.99'))
(39, Decimal('9.99'))
(40, Decimal('8.99'))
(40, Decimal('9.99'))
(41, Decimal('9.99'))
(44, Decimal('9.99'))
(44, Decimal('8.99'))
(45, Decimal('9.99'))
(45, Decimal('8.99'))
(45, Decimal('10.99'))
(46, Decimal('8.99'))
(46, Decimal('8.99'))
(47, Decimal('9.99'))
(48, Decimal('9.99'))
(49, Decimal('9.99'))
(49, Decimal('8.99'))
(49, Decimal('10.99'))
(50, Decimal('9.99'))
(50, Decimal('8.99'))
(50, Decimal('10.99'))
(51, Decimal('9.99'))
(53, Decimal('9.99'))
(54, Decimal('10.99'))
(55, Decimal('9.99'))
(56, Decimal('8.99'))
(57, Decimal('9.99'))
(57, Decimal('9.99'))
(57, Decimal('9.99'))
(58, Decimal('9.99'))
(58, Decimal('8.99'))
(59, Decimal('8.99'))
(59, Decimal('8.99'))
(60, Decimal('8.99'))
(60, Decimal('9.98'))
(61, Decimal('9.99'))
(62, Decimal('8.99'))
(63, Decimal('8.99'))
(63, Decimal('8.99'))
(63, Decimal('8.99'))
(65, Decimal('8.99'))
(66, Decimal('8.99'))
(66, Decimal('8.99'))
(67, Decimal('9.99'))
(67, Decimal('8.99'))
(67, Decimal('8.99'))
(68, Decimal('8.99'))
(69, Decimal('8.99'))
(70, Decimal('9.99'))
(71, Decimal('9.99'))
(71, Decimal('8.99'))
(73, Decimal('9.99'))
(75, Decimal('9.99'))
(75, Decimal('8.97'))
(76, Decimal('10.99'))
(77, Decimal('8.99'))
(77, Decimal('9.99'))
(78, Decimal('10.99'))
(78, Decimal('8.99'))
(79, Decimal('9.99'))
(80, Decimal('8.99'))
(80, Decimal('8.99'))
(80, Decimal('8.99'))
(80, Decimal('8.99'))
(81, Decimal('9.99'))
(82, Decimal('8.99'))
(82, Decimal('8.99'))
(82, Decimal('8.99'))
(82, Decimal('9.99'))
(82, Decimal('8.99'))
(84, Decimal('9.99'))
(84, Decimal('8.99'))
(85, Decimal('9.99'))
(85, Decimal('8.99'))
(86, Decimal('9.99'))
(86, Decimal('8.99'))
(86, Decimal('10.99'))
(86, Decimal('8.99'))
(87, Decimal('9.99'))
(87, Decimal('8.99'))
(87, Decimal('8.99'))
(87, Decimal('10.99'))
(88, Decimal('8.99'))
(89, Decimal('8.99'))
(89, Decimal('8.99'))
(90, Decimal('9.99'))
(92, Decimal('8.99'))
(92, Decimal('8.99'))
(93, Decimal('8.99'))
(94, Decimal('8.99'))
(99, Decimal('8.99'))
(100, Decimal('8.99'))
(100, Decimal('8.99'))
(101, Decimal('9.99'))
(101, Decimal('8.99'))
(102, Decimal('8.99'))
(102, Decimal('9.99'))
(103, Decimal('9.99'))
(103, Decimal('8.99'))
(103, Decimal('8.99'))
(104, Decimal('10.99'))
(105, Decimal('8.99'))
(105, Decimal('9.99'))
(106, Decimal('8.99'))
(106, Decimal('8.99'))
(108, Decimal('8.99'))
(108, Decimal('8.99'))
(110, Decimal('8.99'))
(111, Decimal('9.99'))
(112, Decimal('8.99'))
(112, Decimal('8.99'))
(113, Decimal('8.99'))
(114, Decimal('10.99'))
(116, Decimal('11.99'))
(117, Decimal('9.99'))
(119, Decimal('8.99'))
(120, Decimal('9.99'))
(120, Decimal('9.99'))
(120, Decimal('9.99'))
(121, Decimal('8.99'))
(121, Decimal('8.99'))
(121, Decimal('9.99'))
(123, Decimal('8.99'))
(123, Decimal('8.99'))
(124, Decimal('8.99'))
(125, Decimal('9.99'))
(126, Decimal('9.99'))
(127, Decimal('10.99'))
(128, Decimal('8.99'))
(128, Decimal('8.99'))
(129, Decimal('10.99'))
(131, Decimal('9.99'))
(131, Decimal('8.99'))
(131, Decimal('9.99'))
(134, Decimal('9.99'))
(136, Decimal('8.99'))
(136, Decimal('10.99'))
(137, Decimal('8.99'))
(137, Decimal('9.99'))
(138, Decimal('9.99'))
(139, Decimal('9.99'))
(140, Decimal('9.99'))
(140, Decimal('10.99'))
(142, Decimal('8.99'))
(142, Decimal('9.99'))
(144, Decimal('8.99'))
(144, Decimal('9.99'))
(145, Decimal('8.99'))
(147, Decimal('8.99'))
(147, Decimal('8.99'))
(148, Decimal('8.99'))
(148, Decimal('10.99'))
(148, Decimal('9.99'))
(148, Decimal('10.99'))
(148, Decimal('8.99'))
(149, Decimal('10.99'))
(150, Decimal('8.99'))
(150, Decimal('9.99'))
(153, Decimal('9.99'))
(155, Decimal('8.99'))
(156, Decimal('9.99'))
(158, Decimal('8.99'))
(158, Decimal('8.99'))
(159, Decimal('8.99'))
(163, Decimal('10.99'))
(163, Decimal('8.99'))
(164, Decimal('8.99'))
(166, Decimal('8.99'))
(168, Decimal('10.99'))
(168, Decimal('8.99'))
(169, Decimal('8.99'))
(169, Decimal('9.99'))
(170, Decimal('8.99'))
(170, Decimal('9.99'))
(170, Decimal('8.99'))
(171, Decimal('9.99'))
(171, Decimal('9.99'))
(172, Decimal('8.99'))
(173, Decimal('8.99'))
(173, Decimal('8.99'))
(174, Decimal('8.99'))
(176, Decimal('8.99'))
(177, Decimal('9.99'))
(178, Decimal('9.99'))
(178, Decimal('10.99'))
(179, Decimal('8.99'))
(180, Decimal('9.99'))
(180, Decimal('8.99'))
(180, Decimal('8.99'))
(181, Decimal('8.99'))
(181, Decimal('9.99'))
(181, Decimal('8.99'))
(182, Decimal('8.99'))
(184, Decimal('9.99'))
(185, Decimal('9.99'))
(185, Decimal('8.99'))
(186, Decimal('8.99'))
(187, Decimal('10.99'))
(187, Decimal('8.99'))
(187, Decimal('8.99'))
(187, Decimal('9.99'))
(187, Decimal('8.99'))
(187, Decimal('8.99'))
(189, Decimal('9.99'))
(190, Decimal('9.99'))
(193, Decimal('8.99'))
(195, Decimal('11.99'))
(196, Decimal('11.99'))
(196, Decimal('10.99'))
(196, Decimal('8.99'))
(197, Decimal('8.99'))
(197, Decimal('8.99'))
(197, Decimal('9.99'))
(197, Decimal('8.99'))
(199, Decimal('8.99'))
(199, Decimal('8.99'))
(200, Decimal('9.99'))
(200, Decimal('8.99'))
(200, Decimal('10.99'))
(201, Decimal('9.99'))
(202, Decimal('8.99'))
(202, Decimal('8.99'))
(202, Decimal('8.99'))
(203, Decimal('10.99'))
(204, Decimal('11.99'))
(206, Decimal('10.99'))
(206, Decimal('9.99'))
(207, Decimal('9.99'))
(207, Decimal('8.99'))
(207, Decimal('9.99'))
(209, Decimal('9.99'))
(209, Decimal('8.99'))
(209, Decimal('8.99'))
(209, Decimal('9.99'))
(210, Decimal('8.99'))
(210, Decimal('8.99'))
(210, Decimal('8.99'))
(211, Decimal('8.99'))
(211, Decimal('8.99'))
(211, Decimal('8.99'))
(212, Decimal('9.99'))
(212, Decimal('10.99'))
(213, Decimal('8.99'))
(214, Decimal('9.99'))
(215, Decimal('8.99'))
(215, Decimal('8.99'))
(216, Decimal('8.99'))
(217, Decimal('8.99'))
(218, Decimal('8.99'))
(220, Decimal('8.99'))
(220, Decimal('9.99'))
(220, Decimal('10.99'))
(221, Decimal('10.99'))
(221, Decimal('8.99'))
(221, Decimal('8.99'))
(222, Decimal('8.99'))
(222, Decimal('8.99'))
(226, Decimal('9.99'))
(228, Decimal('8.99'))
(228, Decimal('8.99'))
(230, Decimal('8.99'))
(230, Decimal('9.99'))
(231, Decimal('8.99'))
(231, Decimal('9.99'))
(231, Decimal('8.99'))
(232, Decimal('8.99'))
(232, Decimal('10.99'))
(233, Decimal('8.99'))
(236, Decimal('8.99'))
(237, Decimal('8.99'))
(237, Decimal('11.99'))
(237, Decimal('8.99'))
(238, Decimal('8.99'))
(238, Decimal('8.99'))
(239, Decimal('8.99'))
(240, Decimal('8.99'))
(240, Decimal('8.99'))
(242, Decimal('9.99'))
(242, Decimal('9.99'))
(244, Decimal('9.99'))
(244, Decimal('9.99'))
(245, Decimal('8.99'))
(245, Decimal('10.99'))
(246, Decimal('8.99'))
(249, Decimal('9.99'))
(251, Decimal('8.99'))
(255, Decimal('8.99'))
(255, Decimal('8.99'))
(256, Decimal('8.99'))
(258, Decimal('8.99'))
(258, Decimal('9.99'))
(259, Decimal('10.99'))
(260, Decimal('8.99'))
(260, Decimal('10.99'))
(260, Decimal('8.99'))
(261, Decimal('8.99'))
(262, Decimal('8.99'))
(263, Decimal('8.99'))
(263, Decimal('9.99'))
(264, Decimal('8.99'))
(264, Decimal('8.99'))
(265, Decimal('9.99'))
(265, Decimal('8.99'))
(266, Decimal('8.99'))
(267, Decimal('9.99'))
(269, Decimal('9.99'))
(270, Decimal('9.99'))
(271, Decimal('8.99'))
(272, Decimal('10.99'))
(272, Decimal('8.99'))
(273, Decimal('8.99'))
(273, Decimal('8.99'))
(274, Decimal('9.99'))
(274, Decimal('8.99'))
(274, Decimal('8.99'))
(275, Decimal('9.99'))
(276, Decimal('10.99'))
(276, Decimal('8.99'))
(277, Decimal('10.99'))
(278, Decimal('8.99'))
(279, Decimal('9.99'))
(280, Decimal('9.99'))
(280, Decimal('9.99'))
(282, Decimal('8.99'))
(282, Decimal('9.99'))
(284, Decimal('8.99'))
(285, Decimal('9.99'))
(285, Decimal('9.99'))
(285, Decimal('9.99'))
(285, Decimal('8.99'))
(285, Decimal('9.99'))
(286, Decimal('8.99'))
(286, Decimal('9.99'))
(287, Decimal('9.99'))
(288, Decimal('9.99'))
(289, Decimal('10.99'))
(289, Decimal('8.99'))
(289, Decimal('9.99'))
(290, Decimal('8.99'))
(292, Decimal('8.99'))
(292, Decimal('8.99'))
(292, Decimal('10.99'))
(293, Decimal('8.99'))
(293, Decimal('9.99'))
(293, Decimal('9.99'))
(293, Decimal('8.99'))
(295, Decimal('8.99'))
(295, Decimal('9.99'))
(295, Decimal('9.99'))
(295, Decimal('8.99'))
(297, Decimal('8.99'))
(297, Decimal('8.99'))
(297, Decimal('10.99'))
(298, Decimal('8.99'))
(299, Decimal('8.99'))
(299, Decimal('8.99'))
(299, Decimal('9.99'))
(300, Decimal('10.99'))
(300, Decimal('9.99'))
(301, Decimal('10.99'))
(302, Decimal('8.99'))
(303, Decimal('8.99'))
(304, Decimal('10.99'))
(304, Decimal('8.99'))
(305, Decimal('11.99'))
(305, Decimal('8.99'))
(307, Decimal('10.99'))
(308, Decimal('8.99'))
(309, Decimal('9.99'))
(309, Decimal('8.99'))
(310, Decimal('10.99'))
(311, Decimal('8.99'))
(311, Decimal('9.99'))
(311, Decimal('8.99'))
(315, Decimal('8.99'))
(315, Decimal('9.99'))
(316, Decimal('8.99'))
(316, Decimal('8.99'))
(317, Decimal('8.99'))
(317, Decimal('8.99'))
(318, Decimal('9.99'))
(318, Decimal('8.99'))
(319, Decimal('9.99'))
(319, Decimal('8.99'))
(319, Decimal('8.99'))
(321, Decimal('8.99'))
(322, Decimal('8.99'))
(322, Decimal('8.99'))
(322, Decimal('9.99'))
(322, Decimal('8.99'))
(324, Decimal('8.99'))
(325, Decimal('9.99'))
(327, Decimal('9.99'))
(329, Decimal('8.99'))
(331, Decimal('8.99'))
(331, Decimal('10.99'))
(332, Decimal('8.99'))
(332, Decimal('8.99'))
(333, Decimal('10.99'))
(334, Decimal('8.99'))
(335, Decimal('8.99'))
(336, Decimal('8.99'))
(336, Decimal('8.99'))
(336, Decimal('10.99'))
(337, Decimal('8.99'))
(337, Decimal('8.99'))
(340, Decimal('8.99'))
(340, Decimal('9.99'))
(341, Decimal('9.99'))
(341, Decimal('8.99'))
(342, Decimal('8.99'))
(342, Decimal('8.99'))
(343, Decimal('8.99'))
(343, Decimal('9.99'))
(345, Decimal('8.99'))
(345, Decimal('8.99'))
(345, Decimal('10.99'))
(346, Decimal('8.99'))
(346, Decimal('8.99'))
(346, Decimal('8.99'))
(346, Decimal('8.99'))
(347, Decimal('8.99'))
(347, Decimal('8.99'))
(347, Decimal('8.99'))
(347, Decimal('10.99'))
(348, Decimal('8.99'))
(348, Decimal('9.99'))
(348, Decimal('8.99'))
(349, Decimal('8.99'))
(349, Decimal('8.99'))
(354, Decimal('8.99'))
(357, Decimal('8.99'))
(359, Decimal('8.99'))
(359, Decimal('9.99'))
(360, Decimal('9.99'))
(362, Decimal('8.99'))
(362, Decimal('11.99'))
(363, Decimal('8.99'))
(363, Decimal('9.99'))
(364, Decimal('10.99'))
(365, Decimal('8.99'))
(367, Decimal('8.99'))
(367, Decimal('8.99'))
(367, Decimal('10.99'))
(368, Decimal('9.99'))
(368, Decimal('8.99'))
(368, Decimal('8.99'))
(368, Decimal('8.99'))
(371, Decimal('8.99'))
(371, Decimal('8.99'))
(371, Decimal('10.99'))
(371, Decimal('9.99'))
(372, Decimal('8.99'))
(372, Decimal('10.99'))
(372, Decimal('8.99'))
(372, Decimal('9.99'))
(373, Decimal('8.99'))
(374, Decimal('8.99'))
(375, Decimal('8.99'))
(375, Decimal('9.99'))
(376, Decimal('8.99'))
(376, Decimal('8.99'))
(377, Decimal('10.99'))
(377, Decimal('8.99'))
(379, Decimal('8.99'))
(380, Decimal('8.99'))
(380, Decimal('10.99'))
(381, Decimal('8.99'))
(382, Decimal('9.99'))
(383, Decimal('8.99'))
(384, Decimal('9.99'))
(385, Decimal('8.99'))
(385, Decimal('8.99'))
(386, Decimal('8.99'))
(388, Decimal('10.99'))
(389, Decimal('8.99'))
(389, Decimal('9.99'))
(390, Decimal('8.99'))
(392, Decimal('9.99'))
(393, Decimal('8.99'))
(393, Decimal('8.99'))
(394, Decimal('9.99'))
(398, Decimal('9.99'))
(401, Decimal('8.99'))
(403, Decimal('8.99'))
(403, Decimal('9.99'))
(404, Decimal('8.99'))
(404, Decimal('8.99'))
(404, Decimal('10.99'))
(406, Decimal('8.99'))
(407, Decimal('9.99'))
(407, Decimal('9.99'))
(407, Decimal('8.99'))
(409, Decimal('8.99'))
(409, Decimal('8.99'))
(410, Decimal('10.99'))
(410, Decimal('8.99'))
(412, Decimal('8.99'))
(412, Decimal('8.99'))
(412, Decimal('8.99'))
(414, Decimal('9.99'))
(414, Decimal('10.99'))
(415, Decimal('8.99'))
(415, Decimal('8.99'))
(416, Decimal('8.99'))
(417, Decimal('8.99'))
(417, Decimal('9.99'))
(418, Decimal('10.99'))
(420, Decimal('10.99'))
(421, Decimal('8.99'))
(421, Decimal('9.99'))
(422, Decimal('9.99'))
(423, Decimal('8.99'))
(423, Decimal('9.99'))
(423, Decimal('9.99'))
(423, Decimal('9.99'))
(424, Decimal('8.99'))
(424, Decimal('9.99'))
(425, Decimal('8.99'))
(426, Decimal('10.99'))
(426, Decimal('10.99'))
(431, Decimal('8.99'))
(432, Decimal('8.99'))
(433, Decimal('8.99'))
(433, Decimal('10.99'))
(433, Decimal('8.99'))
(434, Decimal('10.99'))
(434, Decimal('9.99'))
(435, Decimal('8.99'))
(436, Decimal('9.99'))
(436, Decimal('9.99'))
(436, Decimal('9.99'))
(436, Decimal('9.99'))
(437, Decimal('8.99'))
(437, Decimal('8.99'))
(438, Decimal('8.99'))
(439, Decimal('9.99'))
(439, Decimal('9.99'))
(440, Decimal('9.99'))
(441, Decimal('8.99'))
(441, Decimal('10.99'))
(442, Decimal('8.99'))
(443, Decimal('8.99'))
(443, Decimal('9.99'))
(444, Decimal('8.99'))
(445, Decimal('8.99'))
(445, Decimal('9.99'))
(446, Decimal('9.99'))
(446, Decimal('8.99'))
(447, Decimal('8.99'))
(448, Decimal('10.99'))
(448, Decimal('8.99'))
(448, Decimal('9.99'))
(448, Decimal('9.99'))
(449, Decimal('8.99'))
(451, Decimal('8.99'))
(451, Decimal('8.99'))
(451, Decimal('8.99'))
(453, Decimal('8.99'))
(454, Decimal('9.99'))
(454, Decimal('9.99'))
(454, Decimal('8.99'))
(454, Decimal('8.99'))
(455, Decimal('8.99'))
(456, Decimal('8.99'))
(457, Decimal('10.99'))
(459, Decimal('9.99'))
(459, Decimal('9.99'))
(459, Decimal('10.99'))
(459, Decimal('10.99'))
(460, Decimal('10.99'))
(460, Decimal('8.99'))
(462, Decimal('9.99'))
(462, Decimal('8.99'))
(462, Decimal('8.99'))
(462, Decimal('8.99'))
(462, Decimal('8.99'))
(464, Decimal('8.99'))
(465, Decimal('8.99'))
(466, Decimal('8.99'))
(467, Decimal('8.99'))
(467, Decimal('9.99'))
(467, Decimal('8.99'))
(467, Decimal('9.99'))
(468, Decimal('8.99'))
(468, Decimal('10.99'))
(468, Decimal('9.99'))
(468, Decimal('9.99'))
(469, Decimal('9.99'))
(469, Decimal('10.99'))
(469, Decimal('9.99'))
(470, Decimal('10.99'))
(470, Decimal('8.99'))
(470, Decimal('8.99'))
(470, Decimal('10.99'))
(471, Decimal('8.99'))
(472, Decimal('8.99'))
(473, Decimal('8.99'))
(474, Decimal('8.99'))
(475, Decimal('9.99'))
(476, Decimal('9.99'))
(477, Decimal('10.99'))
(477, Decimal('10.99'))
(477, Decimal('8.99'))
(478, Decimal('8.99'))
(479, Decimal('8.99'))
(479, Decimal('8.99'))
(479, Decimal('8.99'))
(479, Decimal('8.99'))
(480, Decimal('9.99'))
(480, Decimal('9.99'))
(480, Decimal('9.99'))
(481, Decimal('10.99'))
(482, Decimal('8.99'))
(482, Decimal('8.99'))
(482, Decimal('8.99'))
(483, Decimal('8.99'))
(483, Decimal('9.99'))
(484, Decimal('9.99'))
(484, Decimal('8.99'))
(485, Decimal('8.99'))
(485, Decimal('8.99'))
(486, Decimal('8.99'))
(486, Decimal('8.99'))
(487, Decimal('9.99'))
(488, Decimal('8.99'))
(489, Decimal('9.99'))
(490, Decimal('8.99'))
(491, Decimal('8.99'))
(492, Decimal('9.99'))
(492, Decimal('8.99'))
(494, Decimal('8.99'))
(494, Decimal('9.99'))
(495, Decimal('9.99'))
(497, Decimal('8.99'))
(497, Decimal('9.99'))
(498, Decimal('8.99'))
(499, Decimal('8.99'))
(500, Decimal('8.99'))
(500, Decimal('8.99'))
(502, Decimal('8.99'))
(502, Decimal('8.99'))
(502, Decimal('9.99'))
(504, Decimal('9.99'))
(504, Decimal('9.99'))
(504, Decimal('8.99'))
(505, Decimal('9.99'))
(506, Decimal('8.99'))
(506, Decimal('9.99'))
(506, Decimal('8.99'))
(506, Decimal('9.99'))
(506, Decimal('9.99'))
(508, Decimal('9.99'))
(508, Decimal('8.99'))
(508, Decimal('8.99'))
(509, Decimal('8.99'))
(509, Decimal('8.99'))
(510, Decimal('8.99'))
(510, Decimal('8.99'))
(510, Decimal('8.99'))
(510, Decimal('8.99'))
(510, Decimal('9.99'))
(511, Decimal('10.99'))
(512, Decimal('9.99'))
(512, Decimal('8.99'))
(513, Decimal('9.99'))
(515, Decimal('8.99'))
(515, Decimal('8.99'))
(516, Decimal('10.99'))
(516, Decimal('8.99'))
(517, Decimal('8.99'))
(519, Decimal('8.99'))
(520, Decimal('10.99'))
(522, Decimal('8.99'))
(522, Decimal('9.99'))
(523, Decimal('8.99'))
(524, Decimal('8.99'))
(526, Decimal('10.99'))
(526, Decimal('8.99'))
(526, Decimal('8.99'))
(526, Decimal('9.99'))
(527, Decimal('8.99'))
(528, Decimal('9.99'))
(528, Decimal('8.99'))
(529, Decimal('10.99'))
(529, Decimal('9.99'))
(531, Decimal('10.99'))
(531, Decimal('8.99'))
(532, Decimal('8.99'))
(532, Decimal('8.99'))
(533, Decimal('8.99'))
(533, Decimal('9.99'))
(533, Decimal('8.99'))
(533, Decimal('8.99'))
(535, Decimal('8.99'))
(535, Decimal('8.99'))
(536, Decimal('8.99'))
(536, Decimal('8.99'))
(536, Decimal('8.99'))
(537, Decimal('8.99'))
(537, Decimal('8.99'))
(537, Decimal('8.99'))
(538, Decimal('8.99'))
(538, Decimal('8.99'))
(540, Decimal('8.99'))
(540, Decimal('8.99'))
(541, Decimal('8.99'))
(542, Decimal('10.99'))
(542, Decimal('9.99'))
(542, Decimal('8.99'))
(542, Decimal('9.99'))
(543, Decimal('9.99'))
(544, Decimal('10.99'))
(544, Decimal('9.99'))
(544, Decimal('8.99'))
(545, Decimal('8.99'))
(545, Decimal('10.99'))
(546, Decimal('9.99'))
(547, Decimal('8.99'))
(547, Decimal('8.99'))
(547, Decimal('9.99'))
(549, Decimal('9.99'))
(550, Decimal('9.99'))
(550, Decimal('10.99'))
(550, Decimal('8.99'))
(550, Decimal('10.99'))
(550, Decimal('9.99'))
(551, Decimal('9.99'))
(552, Decimal('8.99'))
(553, Decimal('8.99'))
(554, Decimal('9.99'))
(554, Decimal('8.99'))
(558, Decimal('10.99'))
(558, Decimal('9.99'))
(558, Decimal('9.99'))
(559, Decimal('8.99'))
(560, Decimal('9.99'))
(561, Decimal('10.99'))
(562, Decimal('8.99'))
(562, Decimal('10.99'))
(563, Decimal('9.99'))
(564, Decimal('10.99'))
(564, Decimal('8.99'))
(565, Decimal('10.99'))
(565, Decimal('8.99'))
(566, Decimal('9.99'))
(566, Decimal('8.99'))
(567, Decimal('10.99'))
(569, Decimal('9.99'))
(569, Decimal('8.99'))
(571, Decimal('9.99'))
(571, Decimal('10.99'))
(571, Decimal('8.99'))
(571, Decimal('8.99'))
(572, Decimal('10.99'))
(573, Decimal('9.99'))
(573, Decimal('10.99'))
(575, Decimal('8.99'))
(575, Decimal('8.99'))
(576, Decimal('8.99'))
(576, Decimal('8.99'))
(577, Decimal('8.99'))
(579, Decimal('9.99'))
(579, Decimal('8.99'))
(579, Decimal('9.99'))
(580, Decimal('8.99'))
(581, Decimal('8.99'))
(581, Decimal('8.99'))
(582, Decimal('9.99'))
(583, Decimal('9.99'))
(583, Decimal('9.99'))
(584, Decimal('8.99'))
(585, Decimal('9.99'))
(585, Decimal('8.99'))
(585, Decimal('9.99'))
(586, Decimal('8.99'))
(587, Decimal('8.99'))
(589, Decimal('8.99'))
(589, Decimal('8.99'))
(589, Decimal('9.99'))
(589, Decimal('8.99'))
(590, Decimal('9.99'))
(591, Decimal('11.99'))
(591, Decimal('8.99'))
(591, Decimal('9.99'))
(592, Decimal('11.99'))
(592, Decimal('9.99'))
(592, Decimal('8.99'))
(593, Decimal('8.99'))
(594, Decimal('8.99'))
(594, Decimal('8.99'))
(594, Decimal('8.99'))
(595, Decimal('9.99'))
(595, Decimal('10.99'))
(597, Decimal('8.99'))
(599, Decimal('9.99'))
(599, Decimal('8.99'))

In [31]:
query6 = """
SELECT 
    c.first_name, 
    c.last_name, 
    COUNT(*) AS num_payments
FROM 
    customer c
JOIN 
    payment p ON c.customer_id = p.customer_id
GROUP BY 
    c.customer_id
ORDER BY 
    num_payments DESC
LIMIT 5;
"""
cursor.execute(query6)
result6 = cursor.fetchall()
print("\nQuery 6 Result:")
for row in result6:
    print(row)

Query 6 Result:
('ELEANOR', 'HUNT', 46)
('KARL', 'SEAL', 45)
('MARCIA', 'DEAN', 42)
('CLARA', 'SHAW', 42)
('TAMMY', 'SANDERS', 41)